= Clojure Revelado
Felipe Gonçalves Marques <marques.goncalves.felipe@gmail.com>;
v1, 2016-07-25
:toc: left
:toclevels: 2
:doctype: book
:numbered:
:source-highlighter: pygments
:pygments-style: friendly
:idseparator: -
:idprefix:
:sectlinks:
:imagesdir: ./images
//^:source-highlighter: coderay
//^:listing-caption: Listing


==  Disclaimer

This is a non-professional translation of https://funcool.github.io/clojurescript-unraveled/[ClojureScript Unraveled] to both
Portuguese and _Clojure_, done in a spike of energy and motivation over a week, which means that we may not be very
careful with the translation. However, we tried not to change the content or the opinions of the authors of the
_ClojureScript Unraveled_ book. I really appreciate their book and the fact that it is written under
Creative Commons.


==  Sobre esse livro

Esse livro é uma dupla tradução do livro https://funcool.github.io/clojurescript-unraveled/[ClojureScript Unraveled].
Dupla tradução pois ele foi traduzido do inglês para o português e de _ClojureScript_ para _Clojure_.
O objetivo é obter uma guia extenso das funcionalidades do _Clojure_ em português, democratizando
o acesso a esse conhecimento nos países lusofonos, principalmente no Brasil. 

Ele não é um livro introdutório em programação, pois ele assume que o leitor
tenha experiência em ao menos uma linguagem de programação. Contudo, ele não
assume nenhuma experiência prévia com _Clojure_ ou programação funcional. Por ser uma
tradução, muitos dos links ainda referenciam textos em inglês, mas onde foi possível,
substituí por equivalentes em português.

Por ser uma linguagem não tão difundida como Python, Ruby ou Java, não existe tantos
recursos de _Clojure_ em português, optamos por traduzir esse livro, pois ele cobre
a maior parte das funcionalidades. Talvez ele não seja tão concreto por não fornecer
exemplos reais como mini-projetos, ou tão profundo, entrando nas discussões de como
a língua foi construída. Porém, acho que ele é um bom começo para fornecer material
gratuito sobre _Clojure_.

Por enquanto, somente o capítulo "A Linguagem (o básico)" foi traduzido. Em breve, pretendo
traduzir os outros capítulos do livro que são: "Ferramentas" e "A Linguagem (avançado)".


== Introdução


 _Clojure_ é uma linguagem funcional e dinâmicamente tipada, e direcionada por dados
 (data-driven). Ela foca em ser pratica, por isso foi implementada para a _Java Virtual Machine(JVM)_.
 Clojure é um dialeto de _LISP_ e por tanto oferece todo o poder de macros e da idea de código é dados.

Antes de começarmos, vamos resumir alguma das ideias mais importantes que ClojureScript
traz. Não se preocupe se não entendê-las de primeira, elas vão ficar claras ao longo desse
livro.

- Clojure favore o paradigma de programção funcional através das suas decisões de design
e idiomas. Apesar de ser assertiva em relação ao paradigma funcional,
ela é uma linguagem pragmática: ao invés de buscar uma pureza em relação a programação funcional
como Haskell, por exemplo, ela foca em ser prática.
- Encoraja programação utilizando estruturas imutáveis, oferencendo implementações
de estruturas de dados altamente performáticas.
- Ela faz uma distinção clara entre identidade e o seu estado, com ferramentas explícitas 
para o gerenciamento de mudanças vinculadas a uma identidade, que é mantida como
uma série de valores imutáveis ao longo do tempo.
- Ela possui um polimorfismo baseado em tipos e valores, que resolve o problema de
expressar o domínio de forma elegante.
- Ela é um dialeto de Lisp, onde programas são escritos utilizando as mesmas
estruturas de dados presentes na língua, uma propriedade conhecida como _homoiconicity_
que torna a meta-programação (programas que escrevem programas) mais simples e palpável.

Essas ideias influenciam a maneira como desenhamos e implementamos nossos programas,
mesmo quando não estamos usando Clojure. Programação funciona, desacoplamento dos dados
das operação que os transformam e ferramentas explícitas para gerenciamento de mudanças
trazem uma grande simplicidade para os sistemas que escrevemos.

[quote, Rich Hickey]
Podemos fazer os mesmos softwares que fazemos hoje com ferramentas drasticamente
mais simples - linguagems, ferramentas, técnicas e abordagens muito mais simples.


 É de longe uma das linguages que mais gostamos de utilizar e nos sintimos extremamente produtivos
 quando a usamos. Espero que você também se sinta assim quando estiver trabalhando com Clojure :).

== A Linguagem (o básico)

Esse capítulo é uma pequena introdução ao Clojure sem assumir nenhum conhecimento
prévio da linguagem, ele provê um tour rápido sobre as principais coisas que
você precisa saber sobre Clojure para entender o resto do livro.

Você pode rodar os trechos de código na REPL online interativa em:
https://repl.it/languages/clojure

/* todo: adicionar tutorial de como rodar clojure */

include::language-basics.adoc[]


== Agradecimentos

Agradecimentos especiais aos autores originais do livro que fizeram o grande trabalho de escrevê-lo
e disponibilizá-lo sob um licensa que permita sua tradução e adaptação.

include::acknowledgments.adoc[]
- Andrey Antukh niwi@niwi.nz
- Alejandro Gómez alejandro@dialelo.com

== Recursos adicionais

Aqui está uma lista de mais recursos sobre _Clojure_.
A medida que acharmos ou produzirmos mais conteúdo em português, iremos adicionar
aqui.

* https://clojure.org/api/cheatsheet/[Clojure Cheatsheet]: uma referência em inglês da linguagem _Clojure_.
* https://clojuredocs.org/[Clojure Community-docs ]: documentação sobre a linguagem produzida pela comunidade.

