= Clojure Unraveled
Felipe Gonçalves Marques <marques.goncalves.felipe@gmail.com>;
v6, 2016-07-25
:toc: left
:toclevels: 2
:doctype: book
:numbered:
:source-highlighter: pygments
:pygments-style: friendly
:idseparator: -
:idprefix:
:sectlinks:
:imagesdir: ./images
//^:source-highlighter: coderay
//^:listing-caption: Listing


==  Sobre esse livro

This book covers the ClojureScript programming language, serves as a detailed guide
of its tooling for development, and presents a series of articles about topics that
are applicable to day-to-day programming in ClojureScript.

It is not an introductory book to programming in that it assumes the reader has
experience programming in at least one language. However, it doesn't assume
experience with _Clojure_ or functional programming. We'll try to include links to
reference material when talking about the theoretical underpinnings of ClojureScript
that may not be familiar to everyone.

Since the ClojureScript documentation is good but sparse, we wanted to write a
compendium of reference information and extensive examples to serve as a
ClojureScript primer as well as a series of practical how-to's. This document will
evolve with the ClojureScript language, both as a reference of the language features
and as a sort of cookbook with practical programming recipes.

You'll get the most out of this book if you:

- are curious about ClojureScript or functional programming and have some programming
  experience;
- write JavaScript or any other language that compiles to it and want to know what
  ClojureScript has to offer;
- already know some Clojure and want to learn how ClojureScript differs from it, plus
  practical topics like how to target both languages with the same code base.

Don't be turned off if you don't see yourself in any of the above groups. We
encourage you to give this book a try and to give us feedback on how we can make it
more accessible.  Our goal is to make ClojureScript more friendly to newcomers and
spread the ideas about programming that Clojure has helped popularize, as we see a
lot of value in them.

This is a list of translations of the book:

- Ukrainian: https://lambdabooks.github.io/clojurescript-unraveled/


== Introdução


 _Clojure_ é uma linguagem funcional e dinâmicamente tipada, e direcionada por dados
 (data-driven). Ela foca em ser pratica, por isso foi implementada para a _Java Virtual Machine(JVM)_.
 Clojure é um dialeto de _LISP_ e por tanto oferece todo o poder de macros e da idea de código é dados.

Antes de começarmos, vamos resumir alguma das ideias mais importantes que ClojureScript
traz. Não se preocupe se não entendê-las de primeira, elas vão ficar claras ao longo desse
livro.

- Clojure favore o paradigma de programção funcional através das suas decisões de design
e idiomas. Apesar de ser assertiva em relação ao paradigma funcional,
ela é uma linguagem pragmática: ao invés de buscar uma pureza em relação a programação funcional
como Haskell, por exemplo, ela foca em ser prática.
- Encoraja programação utilizando estruturas imutáveis, oferencendo implementações
de estruturas de dados altamente performáticas.
- Ela faz uma distinção clara entre identidade e o seu estado, com ferramentas explícitas 
para o gerenciamento de mudanças vinculadas a uma identidade, que é mantida como
uma série de valores imutáveis ao longo do tempo.
- Ela possui um polimorfismo baseado em tipos e valores, que resolve o problema de
expressar o domínio de forma elegante.
- Ela é um dialeto de Lisp, onde programas são escritos utilizando as mesmas
estruturas de dados presentes na língua, uma propriedade conhecida como _homoiconicity_
que torna a meta-programação (programas que escrevem programas) mais simples e palpável.

Essas ideias influenciam a maneira como desenhamos e implementamos nossos programas,
mesmo quando não estamos usando Clojure. Programação funciona, desacoplamento dos dados
das operação que os transformam e ferramentas explícitas para gerenciamento de mudanças
trazem uma grande simplicidade para os sistemas que escrevemos.

[quote, Rich Hickey]
Podemos fazer os mesmos softwares que fazemos hoje com ferramentas drasticamente
mais simples - linguagems, ferramentas, técnicas e abordagens muito mais simples.


 É de longe uma das linguages que mais gostamos de utilizar e nos sintimos extremamente produtivos
 quando a usamos. Espero que você também se sinta assim quando estiver trabalhando com Clojure :).

== A Linguagem (o básico)

Esse capítulo é uma pequena introdução ao Clojure sem assumir nenhum conhecimento
prévio da linguagem, ele provê um tour rápido sobre as principais coisas que
você precisa saber sobre Clojure para entender o resto do livro.

Você pode rodar os trechos de código na REPL online interativa em:
https://repl.it/languages/clojure

/* todo: adicionar tutorial de como rodar clojure */

include::language-basics.adoc[]


== Tooling & Compiler

This chapter will cover a little introduction to existing tooling for making things
easy when developing using ClojureScript. It will cover:

* Using the REPL
* Leiningen and cljsbuild
* Google Closure Library
* Modules
* Unit testing
* Library development
* Browser based development
* Server based development

Unlike the previous chapter, this chapter intends to tell different stories each
independent of the other.

include::compiler.adoc[]


== Language (advanced topics)

This chapter intends to explain some advanced topics that are part of the language
and that does not fit in the first chapter. The good candidates for this section are
transducers, core protocols, transients, metadata. In summary: topics that are not
mandatory for understand the language.

include::language-advanced.adoc[]


== Appendix

include::appendix.adoc[]


== Acknowledgments

include::acknowledgments.adoc[]


== Further Reading

Here is a list of more resources about ClojureScript.

* https://github.com/clojure/clojurescript/wiki[ClojureScript wiki]: a community-mantained wiki about ClojureScript.
* https://github.com/cljsinfo/cljs-api-docs/blob/catalog/INDEX.md[API Reference]: a community-maintained complete language api reference.
* http://cljs.info/cheatsheet/[ClojureScript Cheatsheet]: a comprehensive reference of the ClojureScript language.
* http://catcode.com/etudes-for-clojurescript/toc.html[Études for ClojureScript]: a collection of exercises for learning ClojureScript.
* http://clojurescriptmadeeasy.com/[ClojureScript made easy]: a collection of short articles about solving common problems in ClojureScript.
* http://google.github.io/closure-library/api/[The Google Closure Library API reference]
